name: Publish Site

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: Colstuwjx/Colstuwjx.github.io@develop
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          branch: master
          siteDir: /github/workspace/public
